#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLNV_LINQ
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLNS_LINQ")]
	public partial class QLNSDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    #endregion
		
		public QLNSDataContext() : 
				base(global::QLNV_LINQ.Properties.Settings.Default.QLNS_LINQConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLNSDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<PHONGBAN> PHONGBANs
		{
			get
			{
				return this.GetTable<PHONGBAN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Mã_nhân_viên;
		
		private string _Họ_tên;
		
		private System.Nullable<System.DateTime> _Ngày_sinh;
		
		private string _Giới_tính;
		
		private string _Số_điện_thoại;
		
		private string _Phòng_ban;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMã_nhân_viênChanging(string value);
    partial void OnMã_nhân_viênChanged();
    partial void OnHọ_tênChanging(string value);
    partial void OnHọ_tênChanged();
    partial void OnNgày_sinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgày_sinhChanged();
    partial void OnGiới_tínhChanging(string value);
    partial void OnGiới_tínhChanged();
    partial void OnSố_điện_thoạiChanging(string value);
    partial void OnSố_điện_thoạiChanged();
    partial void OnPhòng_banChanging(string value);
    partial void OnPhòng_banChanged();
    #endregion
		
		public NHANVIEN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã nhân viên]", Storage="_Mã_nhân_viên", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mã_nhân_viên
		{
			get
			{
				return this._Mã_nhân_viên;
			}
			set
			{
				if ((this._Mã_nhân_viên != value))
				{
					this.OnMã_nhân_viênChanging(value);
					this.SendPropertyChanging();
					this._Mã_nhân_viên = value;
					this.SendPropertyChanged("Mã_nhân_viên");
					this.OnMã_nhân_viênChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Họ tên]", Storage="_Họ_tên", DbType="NVarChar(50)")]
		public string Họ_tên
		{
			get
			{
				return this._Họ_tên;
			}
			set
			{
				if ((this._Họ_tên != value))
				{
					this.OnHọ_tênChanging(value);
					this.SendPropertyChanging();
					this._Họ_tên = value;
					this.SendPropertyChanged("Họ_tên");
					this.OnHọ_tênChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Ngày sinh]", Storage="_Ngày_sinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngày_sinh
		{
			get
			{
				return this._Ngày_sinh;
			}
			set
			{
				if ((this._Ngày_sinh != value))
				{
					this.OnNgày_sinhChanging(value);
					this.SendPropertyChanging();
					this._Ngày_sinh = value;
					this.SendPropertyChanged("Ngày_sinh");
					this.OnNgày_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Giới tính]", Storage="_Giới_tính", DbType="NChar(10)")]
		public string Giới_tính
		{
			get
			{
				return this._Giới_tính;
			}
			set
			{
				if ((this._Giới_tính != value))
				{
					this.OnGiới_tínhChanging(value);
					this.SendPropertyChanging();
					this._Giới_tính = value;
					this.SendPropertyChanged("Giới_tính");
					this.OnGiới_tínhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Số điện thoại]", Storage="_Số_điện_thoại", DbType="NChar(10)")]
		public string Số_điện_thoại
		{
			get
			{
				return this._Số_điện_thoại;
			}
			set
			{
				if ((this._Số_điện_thoại != value))
				{
					this.OnSố_điện_thoạiChanging(value);
					this.SendPropertyChanging();
					this._Số_điện_thoại = value;
					this.SendPropertyChanged("Số_điện_thoại");
					this.OnSố_điện_thoạiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phòng ban]", Storage="_Phòng_ban", DbType="NChar(10)")]
		public string Phòng_ban
		{
			get
			{
				return this._Phòng_ban;
			}
			set
			{
				if ((this._Phòng_ban != value))
				{
					this.OnPhòng_banChanging(value);
					this.SendPropertyChanging();
					this._Phòng_ban = value;
					this.SendPropertyChanged("Phòng_ban");
					this.OnPhòng_banChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONGBAN")]
	public partial class PHONGBAN
	{
		
		private string _Mã_phòng_ban;
		
		private string _Tên_phòng_ban;
		
		public PHONGBAN()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Mã phòng ban]", Storage="_Mã_phòng_ban", DbType="NVarChar(50)")]
		public string Mã_phòng_ban
		{
			get
			{
				return this._Mã_phòng_ban;
			}
			set
			{
				if ((this._Mã_phòng_ban != value))
				{
					this._Mã_phòng_ban = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tên phòng ban]", Storage="_Tên_phòng_ban", DbType="NVarChar(50)")]
		public string Tên_phòng_ban
		{
			get
			{
				return this._Tên_phòng_ban;
			}
			set
			{
				if ((this._Tên_phòng_ban != value))
				{
					this._Tên_phòng_ban = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
